export const publicImageMeta: Record<string, { width: number; height: number; srcSet?: string }> = {
  "/academy/ai-intro/malena-button-meme.webp": { width: 1024, height: 1536 },
  "/academy/ai-intro/malena-dragon-queen.webp": { width: 864, height: 1821 },
  "/academy/ai-intro/malena-original-meme.webp": { width: 1024, height: 1024 },
  "/academy/ai-intro/malena-sister-of-battle.webp": { width: 1024, height: 1536 },
  "/academy/ai-intro/malena-twin-blades.webp": { width: 1024, height: 1536 },
  "/academy/ai-intro/malenastrom-gameplay.webp": { width: 1400, height: 788 },
  "/academy/ai-intro/malenastrom-menu.webp": { width: 1400, height: 788 },
  "/academy/ai-intro/mikhail-malena-avatar.webp": { width: 1024, height: 1008 },
  "/academy/ai-intro/mikhail-photo.webp": { width: 292, height: 363 },
  "/academy/ai-intro/mikhail-style-demo.webp": { width: 1124, height: 1399 },
  "/academy/ai-intro/page-final-dark-1440.webp": { width: 1400, height: 933 },
  "/academy/ai-intro/page-final-light-390.webp": { width: 390, height: 1210 },
  "/academy/ai-intro/portfolio-home-author.webp": { width: 1400, height: 681 },
  "/academy/ai-intro/windows-file-extensions.webp": { width: 1400, height: 792 },
  "/academy/ai-intro/workshop-before.webp": {
    width: 1400,
    height: 933,
    srcSet: "/academy/ai-intro/workshop-before-640.webp 640w, /academy/ai-intro/workshop-before.webp 1400w",
  },
  "/academy/ai-intro/workshop-dawn.webp": { width: 1400, height: 933 },
  "/academy/data-driven-speed-modifiers/active-modifier-struct.webp": { width: 1800, height: 956 },
  "/academy/data-driven-speed-modifiers/add-modifier.webp": { width: 1800, height: 956 },
  "/academy/data-driven-speed-modifiers/apply-speed.webp": { width: 1800, height: 956 },
  "/academy/data-driven-speed-modifiers/bp-spawner.webp": { width: 1800, height: 956 },
  "/academy/data-driven-speed-modifiers/component-event-graph.webp": { width: 1800, height: 956 },
  "/academy/data-driven-speed-modifiers/component-tick-interval.webp": { width: 905, height: 450 },
  "/academy/data-driven-speed-modifiers/cover.webp": {
    width: 1280,
    height: 720,
    srcSet: "/academy/data-driven-speed-modifiers/cover-640.webp 640w, /academy/data-driven-speed-modifiers/cover.webp 1280w",
  },
  "/academy/data-driven-speed-modifiers/create-blueprint-types-menu.webp": { width: 1200, height: 703 },
  "/academy/data-driven-speed-modifiers/create-data-asset-menu.webp": { width: 908, height: 595 },
  "/academy/data-driven-speed-modifiers/create-primary-data-asset.webp": { width: 620, height: 534 },
  "/academy/data-driven-speed-modifiers/create-used-modifier-ids-set.webp": { width: 1055, height: 576 },
  "/academy/data-driven-speed-modifiers/final-result-overview.webp": { width: 1800, height: 956 },
  "/academy/data-driven-speed-modifiers/find-modifier-index.webp": { width: 1800, height: 956 },
  "/academy/data-driven-speed-modifiers/modifier-tick.webp": { width: 1800, height: 956 },
  "/academy/data-driven-speed-modifiers/modifier-type-enum.webp": { width: 1800, height: 956 },
  "/academy/data-driven-speed-modifiers/pda-speed-modifier-fields.webp": { width: 1800, height: 956 },
  "/academy/data-driven-speed-modifiers/poison-projectile-owner.webp": { width: 1800, height: 956 },
  "/academy/data-driven-speed-modifiers/recalculate-speed.webp": { width: 1800, height: 956 },
  "/academy/data-driven-speed-modifiers/remove-modifier.webp": { width: 1800, height: 956 },
  "/academy/data-driven-speed-modifiers/result-base-600.webp": { width: 1800, height: 956 },
  "/academy/data-driven-speed-modifiers/result-poison-swamp-280.webp": { width: 1800, height: 956 },
  "/academy/data-driven-speed-modifiers/result-swamp-300.webp": { width: 1800, height: 956 },
  "/academy/data-driven-speed-modifiers/result-two-swamps-300.webp": { width: 1800, height: 956 },
  "/academy/data-driven-speed-modifiers/select-speed-modifier-data-asset.webp": { width: 1149, height: 379 },
  "/academy/data-driven-speed-modifiers/stack-policy-enum.webp": { width: 1800, height: 956 },
  "/academy/data-driven-speed-modifiers/swamp-overlap.webp": { width: 1800, height: 956 },
  "/academy/ue-localization/01-result-en.webp": { width: 1283, height: 724 },
  "/academy/ue-localization/01-result-ru.webp": { width: 1284, height: 724 },
  "/academy/ue-localization/02-st-name.webp": { width: 1920, height: 280 },
  "/academy/ue-localization/03-bind-text-to-string-table.webp": { width: 1920, height: 1080 },
  "/academy/ue-localization/04-cultures-and-gather.webp": { width: 1920, height: 1080 },
  "/academy/ue-localization/04-gather-settings.webp": { width: 1920, height: 1080 },
  "/academy/ue-localization/05-open-russian-translations.webp": { width: 1919, height: 1079 },
  "/academy/ue-localization/05-translation-editor.webp": { width: 1920, height: 1080 },
  "/academy/ue-localization/06-set-current-culture-blueprint.webp": { width: 790, height: 550 },
  "/academy/ue-localization/07-sound-wave-subtitle.webp": { width: 1920, height: 1080 },
  "/academy/ue-localization/08-umg-language-preview.webp": { width: 1920, height: 1080 },
  "/academy/ue-localization/09-create-localized-sound.webp": { width: 1920, height: 1080 },
  "/academy/ue-localization/09-localized-sound-path.webp": { width: 1920, height: 1080 },
  "/academy/ue-localization/09-reimport-localized-sound.webp": { width: 1032, height: 657 },
  "/academy/ue-localization/10-create-localized-texture.webp": { width: 1920, height: 1080 },
  "/academy/ue-localization/11-final-gather-translate-compile.webp": { width: 1920, height: 1080 },
  "/academy/ue-localization/11-localizations-to-package.webp": { width: 1920, height: 1080 },
  "/academy/ue-localization/cover.webp": {
    width: 1280,
    height: 720,
    srcSet: "/academy/ue-localization/cover-640.webp 640w, /academy/ue-localization/cover.webp 1280w",
  },
};

export const publicImageSize = (src?: string) => {
  if (!src) return {};
  const size = publicImageMeta[src];
  if (!size) return {};
  return {
    width: size.width,
    height: size.height,
    ...(size.srcSet ? { srcSet: size.srcSet } : {}),
  };
};
